
{$MODESWITCH ALLOWINLINE+} {Allow inline procedures}
{$MODESWITCH EXCEPTIONS-} {Allow the use of exceptions}

{.$MODESWITCH RESULT+} {Enable the Result identifier for function results}
{.$MODESWITCH DEFAULTPARAMETERS+} {Allow use of default parameter values}
{.$MODESWITCH INITFINAL+} {Allow use of Initialization and Finalization}
{.$MODESWITCH ADVANCEDRECORDS+} {Allow the use of advanced records}
{.$MODESWITCH OUT+} {Allow use of the out parameter type}
{.$MODESWITCH OBJPAS-} {Automatically include the ObjPas unit}



